"""Add user following system and reputation

Revision ID: 88760ef307b6
Revises: 82b7ba5ce9f1
Create Date: 2025-12-18 10:26:38.958117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88760ef307b6'
down_revision = '82b7ba5ce9f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('followed_id', sa.Integer(), nullable=False),
    sa.Column('followed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('follower_id', 'followed_id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reputation_points', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('reputation_points')

    op.drop_table('followers')
    # ### end Alembic commands ###
